
name: Build and Deploy

on:
  push:
    branches:
      - deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v1
    - name: Set up vsce
      run: npm install -g vsce
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: |
        chmod +x gradlew
        ./gradlew build
        ./gradlew installServer
    - name: Create fix extension
      working-directory: metafix-vsc/
      run: |
        npm install
        vsce package -o fix.vsix
    - name: Pushes vsix to GitHub Pages
      uses: dmnemec/copy_file_to_another_repo_action@v1.0.4
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'metafix-vsc/fix.vsix'
        destination_repo: 'metafacture/metafacture.github.io'
        destination_branch: main
        destination_folder: 'ide-extensions'
        user_email: '${{ github.actor }}@users.noreply.github.com'
        user_name: '${{ github.actor }}'
